# Python - fetch_api_data Function

**Generated by GenAI Studio** - 2025-09-07 02:33:50

## Description
Python - fetch_api_data Function

## Programming Language
Python

## Code

```python
import requests
from datetime import datetime

def fetch_api_data(url, params=None):
    """Fetch data from an API endpoint with error handling"""
    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"API request failed: {e}")
        return None

# Example usage
if __name__ == "__main__":
    data = fetch_api_data("https://api.example.com/data", {"limit": 10})
    if data:
        print(f"Fetched {len(data)} items")
```

## Usage
This code example demonstrates key concepts in python programming and can be used as a reference for similar implementations.

---
*This file is part of The GenAI Revolution code examples collection.*
