# Python - retrieve Function

**Generated by GenAI Studio** - 2025-09-07 11:45:20

## Description
Python - retrieve Function

## Programming Language
Python

## Code

```python
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

def retrieve(query):
    inputs = tokenizer(query, return_tensors='pt')
    outputs = model(**inputs)
    return outputs
```

## Usage
This code example demonstrates key concepts in python programming and can be used as a reference for similar implementations.

---
*This file is part of The GenAI Revolution code examples collection.*
