# Initialize LangFuse with your API key

**Generated by GenAI Studio** - 2025-09-16 20:43:27

## Description
Initialize LangFuse with your API key

## Programming Language
Python

## Code

```python
from langfuse import LangFuse

# Initialize LangFuse with your API key
lf = LangFuse(api_key='your_api_key')

# Trace an LLM interaction
response = lf.trace_interaction(
    input_data="What is the weather today?",
    output_data="The weather is sunny with a high of 25°C."
)

# Print the response to verify the trace
print(response)
```

## Usage
This code example demonstrates key concepts in python programming and can be used as a reference for similar implementations.

---
*This file is part of The GenAI Revolution code examples collection.*
