# Initialize LangFuse with your API key

**Generated by GenAI Studio** - 2025-09-16 19:12:16

## Description
Initialize LangFuse with your API key

## Programming Language
Python

## Code

```python
from langfuse import LangFuse

# Initialize LangFuse with your API key
lf = LangFuse(api_key='your_api_key')

# Trace an interaction with input and output data
response = lf.trace_interaction(input_data='Hello, world!', output_data='Hi there!')

# Print the response to verify the trace
print(response)
```

## Usage
This code example demonstrates key concepts in python programming and can be used as a reference for similar implementations.

---
*This file is part of The GenAI Revolution code examples collection.*
